# Generated by Django 6.0.4 on 2026-05-14 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=255)),
                ('waypoints', models.JSONField(default=list)),
                ('end_point', models.CharField(max_length=255)),
                ('estimated_time_minutes', models.IntegerField()),
                ('distance_km', models.FloatField()),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='navigation', to='api.destination')),
            ],
        ),
    ]
